services:
  app:
    healthcheck:
      test: 'curl --fail 127.0.0.1:8000'
    depends_on:
      phpfpm:
        condition: service_started

  phpfpm:
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  db:
    healthcheck:
      test: 'mysqladmin ping -h localhost -u root -pmagento'
      interval: 5s
      timeout: 5s
      retries: 30

  elasticsearch:
    healthcheck:
      test: 'curl --fail elasticsearch:9200/_cat/health >/dev/null || exit 1'
      interval: 5s
      timeout: 5s
      retries: 30
